resources:
 - cert_issuer.yaml
 - tenant.yaml
 - openebs-operator.yaml
 - ingress_minio_tenant.yaml
 - dask-operator.yaml
 - jhub-cluster_role.yaml
 - jhub_deployment.yaml
 - jhub-ingress.yaml

configMapGenerator:
- name: jhub-config
  namespace: default
  files:
    - ./config/jupyterhub_config.py
