apiVersion: v1
kind: Namespace
metadata:
  name: minio 
---
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  creationTimestamp: null
  name: minio-sosc22-users
  namespace: minio
scheduler:
  name: ""
spec:
  certConfig:
    commonName: '*.minio-sosc22-users-hl.minio.svc.cluster.local'
    dnsNames:
    - minio-sosc22-users-ss-0-0.minio-sosc22-users-hl.minio.svc.cluster.local
    organizationName:
    - system:nodes
  configuration:
    name: minio-sosc22-users-env-configuration
  exposeServices: {}
  image: quay.io/minio/minio
  imagePullPolicy: IfNotPresent
  imagePullSecret: {}
  log:
    audit:
      diskCapacityGB: 5
    db:
      image: library/postgres:13
      initimage: busybox:1.33.1
      resources: {}
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
          name: minio-sosc22-users-log
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: "5368709120"
          storageClassName: openebs-hostpath
        status: {}
    image: minio/operator:v4.5.8
    resources: {}
  mountPath: /export
  podManagementPolicy: Parallel
  pools:
  - affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: v1.min.io/tenant
              operator: In
              values:
              - minio-sosc22-users
          topologyKey: kubernetes.io/hostname
    name: ss-0
    resources: {}
    servers: 1
    volumeClaimTemplate:
      apiVersion: v1
      kind: persistentvolumeclaims
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
        storageClassName: openebs-hostpath
      status: {}
    volumesPerServer: 1
  prometheus:
    diskCapacityGB: 5
    image: quay.io/prometheus/prometheus:latest
    initimage: busybox:1.33.1
    resources: {}
    sidecarimage: alpine
    storageClassName: openebs-hostpath
  requestAutoCert: true
  users:
  - name: minio-sosc22-users-user-1
status:
  availableReplicas: 0
  certificates: {}
  currentState: ""
  pools: null
  revision: 0
  syncVersion: ""
  usage: {}

---
apiVersion: v1
data:
  config.env: ZXhwb3J0IE1JTklPX1JPT1RfVVNFUj0iVTVIQ0wzU1RXMzNHTjk1NUxZN0EiCmV4cG9ydCBNSU5JT19ST09UX1BBU1NXT1JEPSJJWGtUc0NIbjczb2R3Nld2cHM2RFkxdzJHa1Q0SlpsVllWWmxaNDRtIgo=
kind: Secret
metadata:
  creationTimestamp: null
  name: minio-sosc22-users-env-configuration
  namespace: minio

---
apiVersion: v1
data:
  CONSOLE_ACCESS_KEY: TjkwQjRWQTg3TDlTQlpNMFVFVVA=
  CONSOLE_SECRET_KEY: aXloQmJaRWh2UGxHWFlhcXNNVkNJSkJXTGlFYUVLRkpOUWxhUXBySQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: minio-sosc22-users-user-1
  namespace: minio

